{% set name = "dftd4" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/releases/download/v{{ version }}/dftd4-{{ version }}-source.tar.xz
  sha256: d2bab992b5ef999fd13fec8eb1da9e9e8d94b8727a2e624d176086197a00a46f

build:
  number: 0
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - cmake  # [win]
    - asciidoctor  # [unix]
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib

test:
  requires:
    - pkg-config
  commands:
    - {{ name }} --version  # [build_platform == target_platform]
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - set PKG_CONFIG_PATH=%PREFIX%\lib\pkgconfig  # [win]
    - pkg-config {{ name }} --exact-version {{ version }}

about:
  home: https://github.com/dftd4/dftd4
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A generally applicable London dispersion correction
  description: |
    This program implements the D4 London dispersion correction
    for molecular and 3D periodic systems.
  doc_url: https://dftd4.github.io/dftd4

extra:
  recipe-maintainers:
    - awvwgk
